"""Apple-local, range-streamed DeepSeek-V4 runtime.

The runtime deliberately keeps model acquisition separate from execution:
``Streamer`` supplies exact safetensors ranges while this package implements
the model math.  No complete checkpoint is required on disk or in memory.
"""

from .config import DeepSeekV4Config
from .causal_weights import (
    CAUSAL_TENSOR_BINDING_SCHEMA,
    CAUSAL_WEIGHT_BINDING_SCHEMA,
    CausalTensorBindingReceipt,
    CausalTensorReadReceipt,
    CausalTensorRangesReadReceipt,
    CausalTensorReader,
    CausalWeightBindingReceipt,
    CausalWeightConflictError,
    CausalWeightError,
    CausalWeightIdentityError,
    CausalWeightIntegrityError,
    CausalWeightLayoutIdentity,
    CausalWeightLeaf,
    CausalWeightMount,
    CausalWeightNotFoundError,
    CausalWeightReadReceipt,
    CausalWeightReader,
    ExpertBindingReceipt,
    LogicalModelIdentity,
    TensorBindingReceipt,
    TensorRangePlan,
    bind_causal_tensor_plans,
    bind_causal_weight_plans,
    semantic_expert_key,
    semantic_tensor_key,
    tensor_range_plan_from_source,
)
from .pager import (
    CausalTensorPlanResolver,
    DeepSeekWeightPager,
    ExpertSourceRange,
    ExpertTensorLayout,
    OfficialExpertRangePlan,
)
from .model import (
    GenerationEvidence,
    OneTokenEvidence,
    StatefulEvidence,
    StreamedDeepSeekV4,
)
from .quantization import (
    dequantize_fp4_e2m1,
    dequantize_fp8_e4m3,
    quantize_dequantize_fp4,
    quantize_dequantize_fp8,
    quantize_fp8_e4m3_parts,
    unpack_fp4_e2m1,
)
from .snapshot import DeepSeekV4SnapshotError, SnapshotLimits
from .semantic_state_cache import (
    AnchorReceipt,
    BOUNDARY_KINDS,
    OrphanGcReceipt,
    RestoredAnchor,
    SemanticStateAnchorCache,
    SemanticStateCacheBudgetError,
    SemanticStateCacheConflict,
    SemanticStateCacheError,
    semantic_label_sha256,
    token_prefix_sha256,
)
from .route_markov import (
    LayerMarkovExpertPredictor,
    LayerMicroWindowPlan,
    MicroWindowPrediction,
    plan_micro_window_prefetch,
)
from .route_model import (
    ROUTE_MODEL_SCHEMA,
    RouteModelArtifact,
    RouteModelArtifactError,
    build_route_model_artifact,
    load_route_model_artifact,
    write_route_model_artifact,
)
from .provenance import runtime_dependency_versions, runtime_source_manifest
from .runtime_source import (
    DeepSeekRuntimeSource,
    DeepSeekRuntimeSourceError,
    GENERAL_DENSE_COVERAGE_CAPABILITY,
    open_deepseek_runtime_source,
    shareable_runtime_evidence,
)
from .layerwise import (
    LAYERWISE_SCHEMA,
    OFFICIAL_SOURCE_SAFE_BYTES,
    LayerwiseError,
    LayerwiseItem,
    LayerwisePlan,
    LayerwiseScorer,
    build_layerwise_plan,
)

__all__ = [
    "AnchorReceipt",
    "BOUNDARY_KINDS",
    "CAUSAL_TENSOR_BINDING_SCHEMA",
    "CAUSAL_WEIGHT_BINDING_SCHEMA",
    "CausalTensorBindingReceipt",
    "CausalTensorPlanResolver",
    "CausalTensorReadReceipt",
    "CausalTensorRangesReadReceipt",
    "CausalTensorReader",
    "CausalWeightBindingReceipt",
    "CausalWeightConflictError",
    "CausalWeightError",
    "CausalWeightIdentityError",
    "CausalWeightIntegrityError",
    "CausalWeightLayoutIdentity",
    "CausalWeightLeaf",
    "CausalWeightMount",
    "CausalWeightNotFoundError",
    "CausalWeightReadReceipt",
    "CausalWeightReader",
    "DeepSeekV4Config",
    "DeepSeekV4SnapshotError",
    "DeepSeekRuntimeSource",
    "DeepSeekRuntimeSourceError",
    "DeepSeekWeightPager",
    "ExpertBindingReceipt",
    "ExpertSourceRange",
    "ExpertTensorLayout",
    "GenerationEvidence",
    "GENERAL_DENSE_COVERAGE_CAPABILITY",
    "LAYERWISE_SCHEMA",
    "LayerwiseError",
    "LayerwiseItem",
    "LayerwisePlan",
    "LayerwiseScorer",
    "LayerMarkovExpertPredictor",
    "LayerMicroWindowPlan",
    "LogicalModelIdentity",
    "OFFICIAL_SOURCE_SAFE_BYTES",
    "OneTokenEvidence",
    "OfficialExpertRangePlan",
    "OrphanGcReceipt",
    "MicroWindowPrediction",
    "ROUTE_MODEL_SCHEMA",
    "RestoredAnchor",
    "RouteModelArtifact",
    "RouteModelArtifactError",
    "StatefulEvidence",
    "SemanticStateAnchorCache",
    "SemanticStateCacheBudgetError",
    "SemanticStateCacheConflict",
    "SemanticStateCacheError",
    "StreamedDeepSeekV4",
    "SnapshotLimits",
    "TensorBindingReceipt",
    "TensorRangePlan",
    "build_layerwise_plan",
    "build_route_model_artifact",
    "bind_causal_weight_plans",
    "bind_causal_tensor_plans",
    "dequantize_fp4_e2m1",
    "dequantize_fp8_e4m3",
    "quantize_dequantize_fp4",
    "quantize_dequantize_fp8",
    "quantize_fp8_e4m3_parts",
    "plan_micro_window_prefetch",
    "open_deepseek_runtime_source",
    "load_route_model_artifact",
    "runtime_dependency_versions",
    "runtime_source_manifest",
    "shareable_runtime_evidence",
    "semantic_expert_key",
    "semantic_label_sha256",
    "semantic_tensor_key",
    "tensor_range_plan_from_source",
    "token_prefix_sha256",
    "unpack_fp4_e2m1",
    "write_route_model_artifact",
]
